#!/usr/bin/openrc-run
# Copyright 2021 Artix Linux
# Distributed under the terms of the GNU General Public License v2

depend() {
    need dbus
    provide logind
    before xdm
}

start() {
    ebegin "Starting elogind"

    start-stop-daemon --start --quiet \
        --pidfile "${ELOGIND_PIDFILE}" \
        --exec "${ELOGIND_EXEC}" -- --daemon
    eend $?
}

stop() {
    ebegin "Stopping elogind"
    start-stop-daemon --stop --quiet --pidfile "${ELOGIND_PIDFILE}"
    eend $?
}
