#!/usr/bin/openrc-run

supervisor=supervise-daemon

name="Music Player Daemon"
description="A daemon for playing music"

command=/usr/bin/mpd
command_args="$MPD_OPTS"
command_args_foreground="--no-daemon"
command_user="mpd:audio"

depend() {
	need localmount
	use net netmount nfsmount esound pulseaudio
	after firewall
} 

start_pre() {
	checkpath --directory --quiet \
		--owner "$command_user" --mode 0775 /var/run/mpd
}
