#!/bin/bash

. /etc/dinit.d/config/hdparm.conf

if grep -qF nohdparm /proc/cmdline; then
    exit 0
fi

for device in /dev/hd* /dev/sd* /dev/cdrom*; do
    [ -e "$device" ] || continue
    case "${device}" in
        *[0-9]) continue ;;
        /dev/hd*)   extra_args="$pata_all_args" ;;
        /dev/sd*)   extra_args="$sata_all_args" ;;
        *)          extra_args="" ;;
    esac

    device_args="${device##*/}_args"
    hdparm "${!device_args}" "$extra_args" "$all_args" "$device"
done
